import 'ActionButton_class.dart';
import 'package:flutter/material.dart';

List<String> presets = ['Ultraschall'];
List buttonListDisplay;
List<ActionButton> buttonList = [
  ActionButton(
    text: 'Mute1',
    buttonColor: Colors.lightGreen,
    textColor: Colors.white,
    clickStatus: false,
    action: 16,
    channel: 1,
    oneClick: false,
    longPress: false,
  ),
  ActionButton(
    text: 'Mute2',
    buttonColor: Colors.lightGreen,
    textColor: Colors.white,
    clickStatus: false,
    action: 17,
    channel: 1,
    oneClick: false,
    longPress: false,
  ),
  ActionButton(
    text: 'Mute3',
    buttonColor: Colors.lightGreen,
    textColor: Colors.white,
    clickStatus: false,
    action: 18,
    channel: 1,
    oneClick: false,
    longPress: false,
  ),
  ActionButton(
    text: 'Mute4',
    buttonColor: Colors.lightGreen,
    textColor: Colors.white,
    clickStatus: false,
    action: 4,
    channel: 1,
    oneClick: false,
    longPress: false,
  ),
  ActionButton(
    text: 'Mute5',
    buttonColor: Colors.lightGreen,
    textColor: Colors.white,
    clickStatus: false,
    action: 5,
    channel: 1,
    oneClick: false,
    longPress: false,
  ),
  ActionButton(
    text: 'Mute6',
    buttonColor: Colors.lightGreen,
    textColor: Colors.white,
    clickStatus: false,
    action: 6,
    channel: 1,
    oneClick: false,
    longPress: false,
  ),
  ActionButton(
    text: 'Mute7',
    buttonColor: Colors.lightGreen,
    textColor: Colors.white,
    clickStatus: false,
    action: 7,
    channel: 1,
    oneClick: false,
    longPress: false,
  ),
  ActionButton(
    text: 'Mute7',
    buttonColor: Colors.lightGreen,
    textColor: Colors.white,
    clickStatus: false,
    action: 8,
    channel: 1,
    oneClick: false,
    longPress: false,
  ),
  ActionButton(
    text: 'Mute7',
    buttonColor: Colors.lightGreen,
    textColor: Colors.white,
    clickStatus: false,
    action: 9,
    channel: 1,
    oneClick: false,
    longPress: false,
  ),
  ActionButton(
    text: 'Mute7',
    buttonColor: Colors.lightGreen,
    textColor: Colors.white,
    clickStatus: false,
    action: 8,
    channel: 1,
    oneClick: false,
    longPress: false,
  ),
  ActionButton(
    text: 'Mute7',
    buttonColor: Colors.lightGreen,
    textColor: Colors.white,
    clickStatus: false,
    action: 7,
    channel: 1,
    oneClick: false,
    longPress: false,
  ),
  ActionButton(
    text: 'Mute7',
    buttonColor: Colors.lightGreen,
    textColor: Colors.white,
    clickStatus: false,
    action: 6,
    channel: 1,
    oneClick: false,
    longPress: false,
  ),
  ActionButton(
    text: 'Mute7',
    buttonColor: Colors.lightGreen,
    textColor: Colors.white,
    clickStatus: false,
    action: 5,
    channel: 1,
    oneClick: false,
    longPress: false,
  ),
  ActionButton(
    text: 'Mute7',
    buttonColor: Colors.lightGreen,
    textColor: Colors.white,
    clickStatus: false,
    action: 4,
    channel: 1,
    oneClick: false,
    longPress: false,
  ),
  ActionButton(
    text: 'Mute7',
    buttonColor: Colors.lightGreen,
    textColor: Colors.white,
    clickStatus: false,
    action: 4,
    channel: 1,
    oneClick: false,
    longPress: false,
  ),
];